### ISSUE TITLE
configure: error: cannot find sources (lib/VMCore/Module.cpp) in .. or ..

### ISSUE THREAD

**Issue by pzz2011** [songlh/perfevo#1]
follow this project's README.md. I got this error:

> configure: error: cannot find sources (lib/VMCore/Module.cpp) in .. or ..
> when I reached the 16th step(int README.md file):
> 1. ../configure --prefix=${LLVM_ROOT}/install/ -with-binutils-include=${LLVM_ROOT}/binutils-2.20.90/include --enable-pic

I cannot find (lib/VMCore/Module.cpp) in llvm-2.8 but llvm-3.7. 
hope you can reply me, any advice will be helpful, thanks!

 我正在上卢山老师的龙芯课程....，所以想看看这些project，谢谢～

**Comment by songlh** [comment]
I just download a llvm-2.8 using the link in README.md. There is Module.cpp in lib/VMCore. Are you sure you are using llvm-2.8, and you are following the link I provide in README.md?

**Comment by pzz2011** [comment]
you are right. I redownload the llvm-2.8. But I got into another problem:

> In file included from /home/zhenzhong/templates/llvm_2.8/llvm-2.8/include/llvm/BasicBlock.h:18:0,
>                  from /home/zhenzhong/templates/llvm_2.8/llvm-2.8/include/llvm/Function.h:23,
>                  from /home/zhenzhong/templates/llvm_2.8/llvm-2.8/lib/ExecutionEngine/JIT/JITDwarfEmitter.cpp:17:
> /home/zhenzhong/templates/llvm_2.8/llvm-2.8/include/llvm/SymbolTableListTraits.h: In member function ‘ItemParentClass\* llvm::SymbolTableListTraits<ValueSubClass, ItemParentClass>::getListOwner()’:
> /home/zhenzhong/templates/llvm_2.8/llvm-2.8/include/llvm/SymbolTableListTraits.h:49:53: warning: typedef ‘Sublist’ locally defined but not used [-Wunused-local-typedefs]
>      typedef iplist<ValueSubClass> ItemParentClass::_Sublist;
>                                                      ^
> make[2]: *_\* [JIT/.makeall] Error 2
> make[1]: **\* [ExecutionEngine/.makeall] Error 2
> make: **\* [all] Error 1

while I executed instuction : 

> make ENABLE_OPTIMIZED=1 -j8

I don't know what happened in you computer now if you execut this instruction(may be a little inconvenient.

**Comment by pzz2011** [comment]
it seems that I need a patch? but I don't which patch it is now.

**Comment by pzz2011** [comment]
I don't why the make ENABLE_OPTIMIZED=1 -j4 command always reported:

> /bin/rm: cannot remove ‘/home/zhenzhong/templates/llvm_2.8/llvm-2.8/build/tools/gold/Release/gold-plugin.d.tmp’: No such file or directory
> /home/zhenzhong/templates/llvm_2.8/llvm-2.8/Makefile.rules:1445: recipe for target '/home/zhenzhong/templates/llvm_2.8/llvm-2.8/build/tools/gold/Release/gold-plugin.o' failed
> make[2]: **\* [/home/zhenzhong/templates/llvm_2.8/llvm-2.8/build/tools/gold/Release/gold-plugin.o] Error 1
> make[2]: Leaving directory '/home/zhenzhong/templates/llvm_2.8/llvm-2.8/build/tools/gold'
> /home/zhenzhong/templates/llvm_2.8/llvm-2.8/Makefile.rules:740: recipe for target 'all' failed
> make[1]: **\* [all] Error 1
> make[1]: **\* Waiting for unfinished jobs....

here, because the binutils-2.20.90 cannot pass the building process(may be caused by my os version or higher gcc version(4.9))), so i used binutils-2.26.51 to replace it. And I'm not sure whether this will cause certain issues to affect the llvm-2.8' building.

**Comment by pzz2011** [comment]
I am really interested in this project... （actually，I have tryed to build this project last year but failed）

**Comment by songlh** [comment]
There is nothing wrong with llvm-2.8, and you do not need to apply any patch. Please downgrade your gcc to 4.4.7 and try the whole process again. For the first problem, you can also simply comment "typedef iplist ItemParentClass::Sublist;" . For the second problem, please delete the build directory and try to build again, or simply remove -j 4 in the command. 

I have not tested binutils-2.26.51 with llvm-2.8, but obviously your current problem has nothing to do with binutils-2.26.51.

**Comment by pzz2011** [comment]
thanks very much.  I have passed the building. But  I don't know how to use it, it seems that this project miss some document about how to use it now.

from the code, and your [homepage](http://pages.cs.wisc.edu/~songlh/perf-detect.html) provided bug list, e.g. [MySQL38968](http://bugs.mysql.com/bug.php?id=38968) I don't know how to set up the environment to use perfevo to analysis bug .

actually， i am know little about llvm.

**Comment by songlh** [comment]
Our checkers are used as normal llvm pass. We do not think we lack any document. Please refer LLVM website (http://llvm.org/) to catch up basic background.
